		SETB P2.1
		SETB P2.0
		MOV A, #11111110B
		MOV P1, A
		ACALL DELAY

HERE :	MOV C,P2.0 ; P2.0 NOT PUSH 
		JNC THERE	; WHEN P2.0 PUSH
		MOV C,P2.1
		JNC WHERE	; WHEN P2.0 NOT AND P2.1 PUSH 
		ACALL HERE

WHERE : RL A
		MOV P1, A
		ACALL DELAY
		MOV C, P2.0
		JC	HERE	; WHEN P2.0 NOT
		MOV C, P1.1
		JC THERE 	; WHEN 0 PUSH 1 NOT
		ACALL OFF 	; WHEN 0 PUSH 1 PUSH		

THERE : MOV C,P2.1	
		JNC OFF		; BOTH PUSH
		RR	A
		MOV P1, A
		ACALL DELAY
		MOV C,P2.0	; CHECK AGAIN
		JC HERE	; WHEN P2.0 NOT PUSH
		ACALL THERE
					

OFF :	MOV P1, #0FFH
		MOV C,P2.0 
		JC	HERE	; IF P2.0 NOT PUSH
		MOV C,P2.1	 
		JC THERE	; P2.0 PUSH & P2.1 NOT
		ACALL OFF
					
DELAY : ;QUARTER SECOND DELAY
		MOV	R5, #250
AGAIN :	MOV	R4, #250
ANDAG :	NOP
		NOP
		DJNZ R4,ANDAG
		DJNZ R5,AGAIN
		RET
	
